### ISSUE TITLE
Run in Docker container

### ISSUE THREAD

**Issue by tlovett1** [nesk/puphpeteer#41]
I want to run PHP on my host machine and run Node/Puppeteer in a Docker container. Has anyone attempted a workflow like that?

**Comment by nesk** [comment]
I don't think anyone publicly shared a docker image for PuPHPeteer, but @GoogleChrome's team [wrote some instructions to run Puppeteer inside Docker](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker), you would only have to add PHP dependencies to make PuPHPeteer run inside Docker.

One day I may provide a Docker image too, but if you want to create one and contribute, you're welcome. 🙂

**Comment by oojacoboo** [comment]
I'm actually wondering this same thing, but don't want puppeteer running in the same docker container as php.  I'm wondering how the communication flow would work between the two docker containers.  I'm guessing you'd need to have some kind of shared directory for the generated PDFs?  I guess that's the part I'm a little fuzzy about.

**Comment by nesk** [comment]
The communication between PHP and Node is done through sockets, PHP runs the `node` command with a script listening on a random localhost port, then PHP connects to this port and starts the communication. The transfered data consists of serialized instructions and values.

PuPHPeteer and Puppeteer should stay in the same docker container because they are tightly coupled, however I think you could install Chromium in another docker container and then use [`puppeteer.connect()`](https://pptr.dev/#?product=Puppeteer&version=v1.13.0&show=api-puppeteerconnectoptions) to define either `browserWSEndpoint` or `browserURL`.

**Comment by oojacoboo** [comment]
Yea, I dug into this at length and concluded the same.  Except, I've found out that, in this scenario, where you want to isolate Node and it's many dependencies from your PHP environment, you're better off just using javascript lib for Puppeteer and keeping everything on that container, then just communicating with Node over http.

**Comment by ivastly** [comment]
Not exactly what this issue is about, however there is docker image with puphpeteer inside https://hub.docker.com/r/vastly/puphpeteer.

**Comment by oojacoboo** [comment]
@ivastly it's about separating out puphpeteer and php from being within the same docker container.
