### ISSUE TITLE
Load website, execute javascript (click button) and fetch following requests

### ISSUE THREAD

**Issue by RosiersRobin** [nesk/puphpeteer#48]
Hi,

I'm trying to push a button, then a video loads and then I want to be able to "log" what the next requests are... Is this possible and how?

Current code I have:

```php
$puppeteer = new Puppeteer(['read_timeout' => 130, 'log_browser_console' => true]);
$browser = $puppeteer->launch();

$page = $browser->newPage();

// Load the website
$page->goto('http://example.com', ['waitUntill' => 'networkidle2']);

// execute the javascript to click an element
$page->click('#PlayerZone > div.placeholder__wrapper > div.player__placeholder.lozad > i > svg');

// Get the response headers


// Close the browser
$browser->close();
```

I hope this is possible and someone is able to help me here!

Kindest regards

Robin

**Comment by nesk** [comment]
This could be possible with the [`request` event](https://pptr.dev/#?product=Puppeteer&version=v1.14.0&show=api-event-request), however since PuPHPeteer [currently doesn't support returning data from an event](https://github.com/nesk/rialto/issues/20), you cannot do this for the moment.

Another solution could be writing the logs to a file, but PuPHPeteer will not allow you to require a module (like `fs`) [until this issue is fixed](https://github.com/nesk/rialto/issues/19).

The only thing that could work today is listening to the [`request` event](https://pptr.dev/#?product=Puppeteer&version=v1.14.0&show=api-event-request) and inside your callback you log the request with `console.log`. By enabling [the `log_node_console` option](https://github.com/nesk/rialto/blob/2403adc6b5f8fd4114d1ec00d9cce2e6ce3a5656/docs/api.md#options) you will receive the logged data in your logger.

**Comment by srhtylmz19** [comment]
any update?
