### ISSUE TITLE
Try catch, is that PHP 7 compatible?

### ISSUE THREAD

**Issue by 7starsone** [nesk/puphpeteer#8]
Hello,
your example in the readme

```
use Nesk\Rialto\Exceptions\Node;

try {
    $page->tryCatch->goto('invalid_url');
} catch (Node\Exception $exception) {
    // Handle the exception...
}
```

is that compatible with PHP 7 or the catch part is just recognized by PHP 5?
thanks

**Comment by nesk** [comment]
The whole project is compatible [only with PHP 7.1+](https://github.com/nesk/puphpeteer/blob/25c699b13d88116eb32fa68a5cade3bee8c8cda3/composer.json#L22). Therefore, the examples I provide in the readme are compatible with the supported versions.

**Comment by 7starsone** [comment]
sorry, don't feel bad 'cause there's no reason. This is not spam at all, this is your project and you can even blame who you want but the issues are there. I wrote everything about the issues and any detail. Even if I follow another schema and write a new issue/bug, unfotunately the details don't change and it's not about "my environment" because any URL has to work. If some URLS, instead, don't work, and the URL structure is the same, there's something wrong...if you or the original Puppeteer, it's not so relevant because many times this project crashes. This should work for any URL and any website (if the HTTP call works, obviously, and if it's a 404, not a crash but a skip...). I think that's easy to understand. Thank you

**Comment by nesk** [comment]
Tell this to the other users and to [my](https://travis-ci.org/nesk/puphpeteer) [tests](https://travis-ci.org/nesk/rialto). You're spamming logs like a madman and won't listen to my advices. And no, you didn't provide me all the details I asked for and you did no research by yourself.

Look, even this issue is a total nonsense, we can clearly see you're not making any efforts…

Congratulations, you're the first person I'm blocking on Github.
